# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# crespo. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that crespo is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.


PRODUCT_PROPERTY_OVERRIDES := \
    rild.libpath=/system/lib/libril-qc-1.so \
    rild.libargs=-d /dev/smd0 \
    persist.rild.nitz_plmn= \
    persist.rild.nitz_long_ons_0= \
    persist.rild.nitz_long_ons_1= \
    persist.rild.nitz_long_ons_2= \
    persist.rild.nitz_long_ons_3= \
    persist.rild.nitz_short_ons_0= \
    persist.rild.nitz_short_ons_1= \
    persist.rild.nitz_short_ons_2= \
    persist.rild.nitz_short_ons_3= \
    ril.subscription.types=NV,RUIM \
    DEVICE_PROVISIONED=1 \
    debug.sf.hw=1 \
    debug.composition.type=mdp \
    persist.cne.UseCne=none \
    persist.cne.bat.range.low.med=30 \
    persist.cne.bat.range.med.high=60 \
    persist.cne.loc.policy.op=/system/etc/OperatorPolicy.xml \
    persist.cne.loc.policy.user=/system/etc/UserPolicy.xml \
    persist.cne.bwbased.rat.sel=false \
    persist.cne.snsr.based.rat.mgt=false \
    persist.cne.bat.based.rat.mgt=false \
    persist.cne.rat.acq.time.out=30000 \
    persist.cne.rat.acq.retry.tout=0 \
    persist.cne.fmc.mode=false \
    persist.cne.fmc.init.time.out=30 \
    persist.cne.fmc.comm.time.out=130 \
    persist.cne.fmc.retry=false \
    media.stagefright.enable-player=true \
    media.stagefright.enable-meta=false \
    media.stagefright.enable-scan=false \
    media.stagefright.enable-http=true \
    ro.opengles.version=131072 \
    ro.use_data_netmgrd=true \
    persist.data.ds_fmc_app.mode=0 \
    persist.ims.regmanager.mode=0 \
    ro.bluetooth.request.master=true \
    ro.qualcomm.bluetooth.ftp=true \
    ro.bluetooth.remote.autoconnect=true \
    debug.bt.discoverable_time=0 \
    persist.omh.enabled=1 \
    ro.config.ehrpd=true \
    ro.qualcomm.cabl=1 \
    ro.sf.lcd_density=240 \
    persist.dsds.enabled=false \
    ro.additionalmounts=/mnt/emmc \
    persist.emmc.sdcard.enabled=0 \
    net.bt.name=Android

# Screen density is actually considered a locale (since it is taken into account
# the the build-time selection of resources). The product definitions including
# this file must pay attention to the fact that the first entry in the final
# PRODUCT_LOCALES expansion must not be a density.
PRODUCT_LOCALES := hdpi

# Maguro blobs expect the following property values. Sneak them into
# /build.prop so that the defaults added to /system/build.prop by the
# build system are ignored (easier than messing around with the core
# build system at the moment.)
#
# TODO: This should eventually be fixed properly by renaming device/
#       directories...
#
ADDITIONAL_DEFAULT_PROPERTIES :=  \
   ro.product.model=msm7627a_sku1 \
   ro.product.brand=qcom \
   ro.product.name=msm7627a_sku1 \
   ro.product.device=msm7627a_sku1 \
   ro.product.board=msm7627a_sku1 \
   ro.build.product=msm7627a_sku1 \



ifeq ($(TARGET_PREBUILT_KERNEL),)
    LOCAL_KERNEL := device/toro/akami/kernel
else
    LOCAL_KERNEL := $(TARGET_PREBUILT_KERNEL)
endif

PRODUCT_COPY_FILES += \
    $(LOCAL_KERNEL):kernel

# See comment at the top of this file. This is where the other
# half of the device-specific product definition file takes care
# of the aspects that require proprietary drivers that aren't
# commonly available
$(call inherit-product-if-exists, vendor/toro/akami/akami-vendor.mk)

